AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'test/test_helper.rb'
    - 'spec/**/*'
    - 'bin/update'
    - 'bin/setup'

Metrics/LineLength:
  Max: 100

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
