AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'test/test_helper.rb'
    - 'spec/**/*'
    - 'bin/update'
    - 'bin/setup'
    - 'app/views/**/*.slim'

Layout/LineLength:
  Max: 100

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 17
